// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// build_M_matrix_cpp
NumericMatrix build_M_matrix_cpp(NumericVector DeltaD_g, int nb_u, int K);
RcppExport SEXP _DistLagHet_build_M_matrix_cpp(SEXP DeltaD_gSEXP, SEXP nb_uSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type DeltaD_g(DeltaD_gSEXP);
    Rcpp::traits::input_parameter< int >::type nb_u(nb_uSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(build_M_matrix_cpp(DeltaD_g, nb_u, K));
    return rcpp_result_gen;
END_RCPP
}
// compute_projection_cpp
Eigen::MatrixXd compute_projection_cpp(Eigen::Map<Eigen::MatrixXd> M_g);
RcppExport SEXP _DistLagHet_compute_projection_cpp(SEXP M_gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type M_g(M_gSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_projection_cpp(M_g));
    return rcpp_result_gen;
END_RCPP
}
// extract_by_indices_cpp
NumericVector extract_by_indices_cpp(NumericVector data, IntegerVector indices);
RcppExport SEXP _DistLagHet_extract_by_indices_cpp(SEXP dataSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_by_indices_cpp(data, indices));
    return rcpp_result_gen;
END_RCPP
}
// phase1_group_cpp
List phase1_group_cpp(NumericVector DeltaY_g, NumericMatrix X_g, NumericVector DeltaD_g, int nb_u, int K, double sqrt_weight);
RcppExport SEXP _DistLagHet_phase1_group_cpp(SEXP DeltaY_gSEXP, SEXP X_gSEXP, SEXP DeltaD_gSEXP, SEXP nb_uSEXP, SEXP KSEXP, SEXP sqrt_weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type DeltaY_g(DeltaY_gSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_g(X_gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DeltaD_g(DeltaD_gSEXP);
    Rcpp::traits::input_parameter< int >::type nb_u(nb_uSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type sqrt_weight(sqrt_weightSEXP);
    rcpp_result_gen = Rcpp::wrap(phase1_group_cpp(DeltaY_g, X_g, DeltaD_g, nb_u, K, sqrt_weight));
    return rcpp_result_gen;
END_RCPP
}
// phase2_group_cpp
List phase2_group_cpp(NumericMatrix M_g, NumericVector DeltaY_Xg_gamma, int K, double weight_j);
RcppExport SEXP _DistLagHet_phase2_group_cpp(SEXP M_gSEXP, SEXP DeltaY_Xg_gammaSEXP, SEXP KSEXP, SEXP weight_jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type M_g(M_gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DeltaY_Xg_gamma(DeltaY_Xg_gammaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type weight_j(weight_jSEXP);
    rcpp_result_gen = Rcpp::wrap(phase2_group_cpp(M_g, DeltaY_Xg_gamma, K, weight_j));
    return rcpp_result_gen;
END_RCPP
}
// estim_RC_model_cpp_full
List estim_RC_model_cpp_full(int K, IntegerVector list_g_data, IntegerVector list_g, NumericVector DeltaY, NumericVector DeltaD, NumericVector D, NumericMatrix X, NumericVector weights, bool same_sample);
RcppExport SEXP _DistLagHet_estim_RC_model_cpp_full(SEXP KSEXP, SEXP list_g_dataSEXP, SEXP list_gSEXP, SEXP DeltaYSEXP, SEXP DeltaDSEXP, SEXP DSEXP, SEXP XSEXP, SEXP weightsSEXP, SEXP same_sampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type list_g_data(list_g_dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type list_g(list_gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DeltaY(DeltaYSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DeltaD(DeltaDSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type D(DSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type same_sample(same_sampleSEXP);
    rcpp_result_gen = Rcpp::wrap(estim_RC_model_cpp_full(K, list_g_data, list_g, DeltaY, DeltaD, D, X, weights, same_sample));
    return rcpp_result_gen;
END_RCPP
}
// build_M_matrix_full_cpp
NumericMatrix build_M_matrix_full_cpp(NumericVector DeltaD_g, int T_periods);
RcppExport SEXP _DistLagHet_build_M_matrix_full_cpp(SEXP DeltaD_gSEXP, SEXP T_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type DeltaD_g(DeltaD_gSEXP);
    Rcpp::traits::input_parameter< int >::type T_periods(T_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(build_M_matrix_full_cpp(DeltaD_g, T_periods));
    return rcpp_result_gen;
END_RCPP
}
// estim_RC_model_full_cpp
List estim_RC_model_full_cpp(int T_periods, IntegerVector list_g_data, IntegerVector list_g, NumericVector DeltaY, NumericVector DeltaD, NumericMatrix X, NumericVector weights, IntegerVector group_sizes, bool same_sample);
RcppExport SEXP _DistLagHet_estim_RC_model_full_cpp(SEXP T_periodsSEXP, SEXP list_g_dataSEXP, SEXP list_gSEXP, SEXP DeltaYSEXP, SEXP DeltaDSEXP, SEXP XSEXP, SEXP weightsSEXP, SEXP group_sizesSEXP, SEXP same_sampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type T_periods(T_periodsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type list_g_data(list_g_dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type list_g(list_gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DeltaY(DeltaYSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DeltaD(DeltaDSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_sizes(group_sizesSEXP);
    Rcpp::traits::input_parameter< bool >::type same_sample(same_sampleSEXP);
    rcpp_result_gen = Rcpp::wrap(estim_RC_model_full_cpp(T_periods, list_g_data, list_g, DeltaY, DeltaD, X, weights, group_sizes, same_sample));
    return rcpp_result_gen;
END_RCPP
}
// build_M_matrix_interactions_cpp
NumericMatrix build_M_matrix_interactions_cpp(NumericVector DeltaD_g, NumericVector D_g, int nb_u, int K);
RcppExport SEXP _DistLagHet_build_M_matrix_interactions_cpp(SEXP DeltaD_gSEXP, SEXP D_gSEXP, SEXP nb_uSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type DeltaD_g(DeltaD_gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type D_g(D_gSEXP);
    Rcpp::traits::input_parameter< int >::type nb_u(nb_uSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(build_M_matrix_interactions_cpp(DeltaD_g, D_g, nb_u, K));
    return rcpp_result_gen;
END_RCPP
}
// estim_RC_model_interactions_cpp
List estim_RC_model_interactions_cpp(int K, IntegerVector list_g_data, IntegerVector list_g, NumericVector DeltaY, NumericVector DeltaD, NumericVector D, NumericMatrix X, NumericVector weights, bool same_sample);
RcppExport SEXP _DistLagHet_estim_RC_model_interactions_cpp(SEXP KSEXP, SEXP list_g_dataSEXP, SEXP list_gSEXP, SEXP DeltaYSEXP, SEXP DeltaDSEXP, SEXP DSEXP, SEXP XSEXP, SEXP weightsSEXP, SEXP same_sampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type list_g_data(list_g_dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type list_g(list_gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DeltaY(DeltaYSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DeltaD(DeltaDSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type D(DSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type same_sample(same_sampleSEXP);
    rcpp_result_gen = Rcpp::wrap(estim_RC_model_interactions_cpp(K, list_g_data, list_g, DeltaY, DeltaD, D, X, weights, same_sample));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DistLagHet_build_M_matrix_cpp", (DL_FUNC) &_DistLagHet_build_M_matrix_cpp, 3},
    {"_DistLagHet_compute_projection_cpp", (DL_FUNC) &_DistLagHet_compute_projection_cpp, 1},
    {"_DistLagHet_extract_by_indices_cpp", (DL_FUNC) &_DistLagHet_extract_by_indices_cpp, 2},
    {"_DistLagHet_phase1_group_cpp", (DL_FUNC) &_DistLagHet_phase1_group_cpp, 6},
    {"_DistLagHet_phase2_group_cpp", (DL_FUNC) &_DistLagHet_phase2_group_cpp, 4},
    {"_DistLagHet_estim_RC_model_cpp_full", (DL_FUNC) &_DistLagHet_estim_RC_model_cpp_full, 9},
    {"_DistLagHet_build_M_matrix_full_cpp", (DL_FUNC) &_DistLagHet_build_M_matrix_full_cpp, 2},
    {"_DistLagHet_estim_RC_model_full_cpp", (DL_FUNC) &_DistLagHet_estim_RC_model_full_cpp, 9},
    {"_DistLagHet_build_M_matrix_interactions_cpp", (DL_FUNC) &_DistLagHet_build_M_matrix_interactions_cpp, 4},
    {"_DistLagHet_estim_RC_model_interactions_cpp", (DL_FUNC) &_DistLagHet_estim_RC_model_interactions_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_DistLagHet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
