# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build M matrix using C++ (vectorized)
#'
#' Fast C++ implementation of M matrix construction for RC model.
#'
#' @param DeltaD_g NumericVector of DeltaD for group g
#' @param nb_u Integer, number of usable observations
#' @param K Integer, number of lags
#' @return NumericMatrix M_g (nb_u x (K+1))
#' @keywords internal
build_M_matrix_cpp <- function(DeltaD_g, nb_u, K) {
    .Call(`_DistLagHet_build_M_matrix_cpp`, DeltaD_g, nb_u, K)
}

#' Compute projection matrix Pi_g efficiently in C++
#'
#' Computes Pi_g = I - M_g %*% ginv(M_g) using Eigen for stability
#'
#' @param M_g NumericMatrix M for group g
#' @return NumericMatrix projection matrix Pi_g
#' @keywords internal
compute_projection_cpp <- function(M_g) {
    .Call(`_DistLagHet_compute_projection_cpp`, M_g)
}

#' Extract group data efficiently in C++
#'
#' Fast extraction of group-specific data
#'
#' @param data NumericVector or NumericMatrix
#' @param indices IntegerVector of indices to extract
#' @return Extracted data
#' @keywords internal
extract_by_indices_cpp <- function(data, indices) {
    .Call(`_DistLagHet_extract_by_indices_cpp`, data, indices)
}

#' Compute weighted projection and store results (Phase 1 loop body)
#'
#' Optimized C++ implementation of the inner Phase 1 loop
#'
#' @param DeltaY_g NumericVector of DeltaY for group g
#' @param X_g NumericMatrix of X for group g (can be empty)
#' @param DeltaD_g NumericVector of DeltaD for group g
#' @param nb_u Integer, number of usable observations
#' @param K Integer, number of lags
#' @param sqrt_weight Double, square root of weight for this group
#' @return List containing M_g, newY_g, newX_g
#' @keywords internal
phase1_group_cpp <- function(DeltaY_g, X_g, DeltaD_g, nb_u, K, sqrt_weight) {
    .Call(`_DistLagHet_phase1_group_cpp`, DeltaY_g, X_g, DeltaD_g, nb_u, K, sqrt_weight)
}

#' Compute beta coefficients for group (Phase 2 loop body)
#'
#' Optimized C++ implementation of Phase 2 beta computation
#'
#' @param M_g NumericMatrix M for group g
#' @param DeltaY_Xg_gamma NumericVector residuals after removing X*gamma
#' @param K Integer, number of lags
#' @param weight_j Double, weight for this group
#' @return List with ind_avg and beta_hat vectors
#' @keywords internal
phase2_group_cpp <- function(M_g, DeltaY_Xg_gamma, K, weight_j) {
    .Call(`_DistLagHet_phase2_group_cpp`, M_g, DeltaY_Xg_gamma, K, weight_j)
}

#' Full RC model estimation in C++ (base model)
#'
#' Complete C++ implementation of the base RC model estimation.
#' This replaces the entire R loop structure with optimized C++ code.
#'
#' @param K Integer, number of lags
#' @param list_g_data IntegerVector, group identifiers for each observation
#' @param list_g IntegerVector, unique group values
#' @param DeltaY NumericVector, outcome differences
#' @param DeltaD NumericVector, treatment differences
#' @param D NumericVector, treatment levels
#' @param X NumericMatrix, covariates (can have 0 columns)
#' @param weights NumericVector, weights for each group
#' @return List with estimation results
#' @keywords internal
estim_RC_model_cpp_full <- function(K, list_g_data, list_g, DeltaY, DeltaD, D, X, weights, same_sample = FALSE) {
    .Call(`_DistLagHet_estim_RC_model_cpp_full`, K, list_g_data, list_g, DeltaY, DeltaD, D, X, weights, same_sample)
}

#' Build lower triangular M matrix for full dynamics model
#'
#' @param DeltaD_g NumericVector of DeltaD for group g
#' @param T_periods Integer, number of periods
#' @return NumericMatrix M_g (T_periods-1 x T_periods-1)
#' @keywords internal
build_M_matrix_full_cpp <- function(DeltaD_g, T_periods) {
    .Call(`_DistLagHet_build_M_matrix_full_cpp`, DeltaD_g, T_periods)
}

#' Full dynamics RC model estimation in C++
#'
#' @param T_periods Integer, number of periods
#' @param list_g_data IntegerVector, group identifiers for each observation
#' @param list_g IntegerVector, unique group values
#' @param DeltaY NumericVector, outcome differences
#' @param DeltaD NumericVector, treatment differences
#' @param X NumericMatrix, covariates
#' @param weights NumericVector, weights for each group
#' @param group_sizes IntegerVector, number of observations per group
#' @return List with estimation results
#' @keywords internal
estim_RC_model_full_cpp <- function(T_periods, list_g_data, list_g, DeltaY, DeltaD, X, weights, group_sizes, same_sample = FALSE) {
    .Call(`_DistLagHet_estim_RC_model_full_cpp`, T_periods, list_g_data, list_g, DeltaY, DeltaD, X, weights, group_sizes, same_sample)
}

#' Build M matrix with interactions for interactions model
#'
#' @param DeltaD_g NumericVector of DeltaD for group g
#' @param D_g NumericVector of D for group g
#' @param nb_u Integer, number of usable observations
#' @param K Integer, number of lags
#' @return NumericMatrix M_g with main effects and interactions
#' @keywords internal
build_M_matrix_interactions_cpp <- function(DeltaD_g, D_g, nb_u, K) {
    .Call(`_DistLagHet_build_M_matrix_interactions_cpp`, DeltaD_g, D_g, nb_u, K)
}

#' Interactions RC model estimation in C++
#'
#' @param K Integer, number of lags
#' @param list_g_data IntegerVector, group identifiers for each observation
#' @param list_g IntegerVector, unique group values
#' @param DeltaY NumericVector, outcome differences
#' @param DeltaD NumericVector, treatment differences
#' @param D NumericVector, treatment levels
#' @param X NumericMatrix, covariates
#' @param weights NumericVector, weights for each group
#' @return List with estimation results
#' @keywords internal
estim_RC_model_interactions_cpp <- function(K, list_g_data, list_g, DeltaY, DeltaD, D, X, weights, same_sample = FALSE) {
    .Call(`_DistLagHet_estim_RC_model_interactions_cpp`, K, list_g_data, list_g, DeltaY, DeltaD, D, X, weights, same_sample)
}

